### ISSUE TITLE
Typo in url

### ISSUE THREAD

**Issue by vladholubiev** [tunnckoCore/tunnckoCore-site-old#4]
`<a href="htts://twitter.com/dwylhq" class="link"><strong>dwyl.io</strong></a>`

**Comment by tunnckoCore** [comment]
oooh, thanks! it's too old, but thanks! :D

**Comment by tunnckoCore** [comment]
fixed in https://github.com/tunnckoCore/tunnckoCore/commit/4b9d8f7750b3f0e3ab51358de2b1be6d3ee1aacc :)
